# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  build-artifacts-1:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads-1
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads-1
          echo 'alpha'    > alpha-1.html
          echo 'bravo'    > bravo-1.html
          echo 'charlie'  > charlie-1.html
          cd ..
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download-1
          path: downloads-1

  build-artifacts-2:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads-2
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads-2
          echo 'alpha'    > alpha-2.html
          echo 'bravo'    > bravo-2.html
          echo 'charlie'  > charlie-2.html
          cd ..
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download-2
          path: downloads-2
          
  download-build-artifacts-1:
    runs-on: ubuntu-latest
    steps:
        
      - name: step 1 - Download artifacts to a temp folder
        uses: actions/download-artifact@v3
        with:
          name: downloads-1
      
      - name: Display structure of downloaded files
        run: ls -R

  download-build-artifacts-2:
    runs-on: ubuntu-latest
    steps:
        
      - name: step 1 - Download artifacts to a temp folder
        uses: actions/download-artifact@v3
        with:
          name: assets-for-downloads-2
      
      - name: Display structure of downloaded files
        run: ls -R
